export const baseUrl = "http://localhost:7001";
// export const baseUrl = "https://darshan-yog-node-apis.onrender.com";

export const pages: any = [
  {
    name: "HOME",
    route: "/",
  },

  // {
  //   name: "KNOWLEDGE",
  //   route: "/knowledge",
  //   // options: [
  //   //   { pageName: "Knowledge", route: "/knowledge" },
  //   //   { pageName: "Veda", route: "veda" },
  //   //   { pageName: "Darshan", route: "darshan" },
  //   //   { pageName: "Yoga", route: "yoga" },
  //   //   { pageName: "The Light of truth", route: "light-of-truth" },
  //   // ],
  // },
  // { name: "PROGRAM SCHEDULE", route: "/program-schedule" },
  // {
  //   name: "CONTACT US",
  //   route: "/contact-us",
  // },
  // {
  //   name: "ABOUT US",
  //   route: "/about-us",
  //   //   options: [
  //   //     {
  //   //       pageName: "About Us",
  //   //       route: "about-us",
  //   //     },
  //   //     {
  //   //       pageName: "Aims & Ideals",
  //   //       route: "/aims-ideals",
  //   //       content: `<div >
  //   //       <h4>About Us</h4>

  //   //       <p></p><p>Swāmi Satyapati ji Parivrājak founded theDarshan Yog MahāVidyālaya on 10 April 1986 (Chaitra Shukla Pratipada, Vikram Samvat 2043), as a unique educational institution solely dedicated for the welfare of the human race, i.e. the physical, moral and spiritual uplift of all. Situated 70 Km north of Ahmedābad, Gujarāt, India, the Vidyālaya is surrounded by a lush greenery (forest and nature).</p>

  //   // <p>Swāmiji has dedicated his life to serve humanity. His words and deeds are in perfect harmony, no divergence. True to his name, he has an unbendable faith in truth. Meticulous in his teaching methodology, he adheres strictly to time schedules and goals.</p>

  //   // <p>Under the leadership of Swāmi Satyapati ji the Darshan Yog MahāVidyālaya emerged as an illustrious training centre for Vaidik scholars, who in turn have dedicated themselves to train a new generation of scholars and disseminate the Sat Sanātan Vaidik Dharma (pristine Vaidik philosophy) in the far corners of India and abroad. The commendable work of Swāmi Satyapati ji wasduly acknowledged through a public felicitation ceremony held in 1999. Swami Ji &nbsp;donated the cheque of Rupees 51 Lakhs presented to him as award to establish the Vānprastha Sādhak Āshram.</p>

  //   // <p>The preceptors (āchāryas) and students (brahmachāris) of the Vidyālaya as well as well-wishers and donors had put up every possible effort to realise the Vānprastha Sādhak Āshram project. With the blessings of the Almighty, their hard work paid off as a real project. Based on the family tree concept, the Vānprastha Sādhak Āshram is indeed the brain child or product of the Darshan Yog MahāVidyālaya.</p>

  //   // <p>The Darshan Yog MahāVidyālaya has at all times maintained the spirit of dedication of its founder and inspiring figure,Swāmi Satyapati Ji Parivrājak. We are committed to empower scholars knowledgeable in Veda, Darshan philosophy and Vaidik Yog to fulfil the spiritual needs of the modern era, a knowledge-based society.</p>

  //   // <p>We extend a cordial invitation to you to spend a few days with us, a real break from the daily rush / routine, relax, meditate and benefit from the silence as well as be one with the nature, take advantage of the pavitra aroma (fragrant / divine atmosphere) emanating from Yajna, listen to the tweeting of birds, taste pure cow milk, etc.</p>

  //   // <p>The āchāryas and brahmachāris of the Vidyālaya would be pleased to answer your spiritual questions.</p>

  //   // <p>Join us to make faster spiritual progress and help others do the same.</p>

  //   // <p>Live life the way God meant.</p>
  //   // <p></p>
  //   //       </div>`,
  //   //     },
  //   //     { pageName: "key information", route: "key-info" },
  //   //     { pageName: "Our Functionary", route: "our-functionary" },
  //   //     { pageName: "Passed Scholar", route: "passed-scholar" },
  //   //     { pageName: "Vision", route: "vision" },
  //   //   ],
  // },
  {
    name: "EVENTS",
    route: "/events",
  },
  {
    name: "LOG IN",
    route: "/log-in",
  },
];

export const ProgramScheduleDataArray: any = [
  // {
  //   avatarLabel: "A",
  //   title: "सरल क्रियात्मक योग प्रशिक्षण शिविर",
  //   subheader: "05/09/2023 to 10/09/2023",
  //   imageSrc:
  //     "https://darshanyog.org/assets/img/upload/program_schedule/OU2dnTEGrd.jpg",
  //   content:
  //     "पूज्य स्वामी विवेकानन्द जी परिव्राजक, आचार्य आत्मन जी, आचार्य प्रियेश जी के सानिध्य में वैदिक शिद्धान्त के परिचय के साथ साथ धारणा, ध्यान, समाधि के क्रियात्मक अभ्यास कराया जाएगा।",
  //   expandContent:
  //     "	गांधीनगर, गुजरात  श्री चन्द्रप्रभ लब्धिधाम तीर्थ, हिम्मतनगर-उदयपुर हाइवे नं-8, चिलोडा चौकड़ी से 5 कि.मी. अंजलि होटल के सामने, गाँव- धणप, गांधीनगर, गुजरात",
  // },
  {
    avatarLabel: "B",
    title: "क्रियात्मक योग प्रशिक्षण शिविर",
    subheader: "05/09/2023 to 10/09/2023",
    imageSrc:
      "https://darshanyog.org/assets/img/upload/program_schedule/rMosf3iHBl.jpeg",
    content:
      "(योगविद्या-ध्यानाभ्यास से सुखद जीवन जीने का कौशल सीखने का पंचदिवसीय आवासीय सुंदर अवसर ) दिनांक : 05/09/2023 से 10/09/2023 श्री चन्द्रप्रभ लब्धिधाम तीर्थ, हिम्मतनगर-उदयपुर हाइवे नं-8, चिलोडा चौकड़ी से 5 कि.मी. अंजलि होटल के सामने, गाँव- धणप, गांधीनगर, गुजरात Location : - https://goo.gl/maps/fz3ypiWy3zYQb8AD6, व्यवस्था शुल्क :- 3000/- (AC आवास कमरे हेतु), 2500/- (Non AC आवास कमरे हेतु) अधिक जानकारी के लिए आचार्य प्रियेश जी (9306374959) से संपर्क करें ।",
    expandContent:
      "गांधीनगर, गुजरात      श्री चन्द्रप्रभ लब्धिधाम तीर्थ, हिम्मतनगर-उदयपुर हाइवे नं-8, चिलोडा चौकड़ी से 5 कि.मी. अंजलि होटल के सामने, गाँव- धणप, गांधीनगर, गुजरात",
  },
];

export const EducationalQualification: any = [
  "10th",
  "12th",
  "BA",
  "B.Tech",
  "MBBS",
  "MBA",
  "CA",
  "LLB",
  "B.Sc.",
  "M.Sc.",
  "B.Com",
  "M.Com",
  "Graduate",
  "Post Graduate",
  "PhD",
  "Diploma",
  "Other",
];

export const Profession = [
  "Banking Professional",
  "Chartered Accountant",
  "Finance Professional",
  "Admin/HR Professional",
  "Media Professional",
  "Event Manager",
  "Farmer",
  "Airline Professional",
  "Architect",
  "Interior Designer",
  "Web/Ux Designer",
  "Fashion Designer",
  "IAS/IFS/IES/IRS/IPS",
  "Defense Professional",
  "Sales&Marketing Professional",
  "Professor",
  "Research Scholar",
  "Teacher",
  "Student",
  "Vedic Scholar",
  "Businessman",
  "Software/IT Engineer",
  "Non IT Engineer",
  "Lawyer",
  "Medical Doctor",
  "Nurse",
  "Poltician",
  "Sportsman",
  "Retired",
  "Not Working",
  "Others",
];

export const states = [
  "Gujarat (गुजरात)",
  "Bihar (बिहार)",
  "Chhattisgarh (छत्तीसगढ़)",
  "Jharkhand (झारखंड)",
  "Rajasthan (राजस्थान)",
  "Arunachal Pradesh (अरुणाचल प्रदेश)",
  "Haryana (हरियाणा)",
  "Odisha (उड़ीसा)",
  "Rajasthan (राजस्थान)",
  "Uttar Pradesh (उत्तर प्रदेश)",
  "Andhra Pradesh (आंध्र प्रदेश)",
  "Goa (गोवा)",
  "Karnataka (कर्नाटक)",
  "Kerala (केरल)",
  "Punjab (पंजाब)",
  "Tamil Nadu (तमिलनाडु)",
  "Telangana (तेलंगाना)",
  "Madhya Pradesh (मध्य प्रदेश)",
  "Maharashtra (महाराष्ट्र)",
  "West Bengal (पश्चिम बंगाल)",
  "Himachal Pradesh (हिमाचल प्रदेश)",
  "Punjab (पंजाब)",
  "Uttarakhand (उत्तराखंड)",
  "Haryana (हरियाणा)",
  "Assam (असम)",
  "Manipur (मणिपुर)",
  "Meghalaya (मेघालय)",
  "Mizoram (मिजोरम)",
  "Nagaland (नागालैंड)",
  "Sikkim (सिक्किम)",
  "Tripura (त्रिपुरा)",
  "Chandigarh (चंडीगढ़)",
  "Delhi (दिल्ली)",
  "Jammu and Kashmir (जम्मू और कश्मीर)*",
  "Puducherry (पुडुचेरी)",
  "Delhi (दिल्ली)",
  "Jammu and Kashmir (जम्मू और कश्मीर)*",
  "Delhi (दिल्ली)",
  "Andaman and Nicobar (अंडमान और निकोबार)",
  "Dadra Nagar Haveli (दादरा और नागर हवेली )",
  "Daman and Diu (दमन और दीव )",
  "Lakshadweep (लक्षद्वीप)",
  "Ladakh (लद्दाख)*",
];

export const statesWithDistricts: any = {
  "Andaman Nicobar": ["Nicobar", "North Middle Andaman", "South Andaman"],
  "Andhra Pradesh": [
    "Anantapur",
    "Chittoor",
    "East Godavari",
    "Guntur",
    "Kadapa",
    "Krishna",
    "Kurnool",
    "Nellore",
    "Prakasam",
    "Srikakulam",
    "Visakhapatnam",
    "Vizianagaram",
    "West Godavari",
  ],
  "Arunachal Pradesh": [
    "Anjaw",
    "Central Siang",
    "Changlang",
    "Dibang Valley",
    "East Kameng",
    "East Siang",
    "Kamle",
    "Kra Daadi",
    "Kurung Kumey",
    "Lepa Rada",
    "Lohit",
    "Longding",
    "Lower Dibang Valley",
    "Lower Siang",
    "Lower Subansiri",
    "Namsai",
    "Pakke Kessang",
    "Papum Pare",
    "Shi Yomi",
    "Tawang",
    "Tirap",
    "Upper Siang",
    "Upper Subansiri",
    "West Kameng",
    "West Siang",
  ],
  Assam: [
    "Baksa",
    "Barpeta",
    "Biswanath",
    "Bongaigaon",
    "Cachar",
    "Charaideo",
    "Chirang",
    "Darrang",
    "Dhemaji",
    "Dhubri",
    "Dibrugarh",
    "Dima Hasao",
    "Goalpara",
    "Golaghat",
    "Hailakandi",
    "Hojai",
    "Jorhat",
    "Kamrup",
    "Kamrup Metropolitan",
    "Karbi Anglong",
    "Karimganj",
    "Kokrajhar",
    "Lakhimpur",
    "Majuli",
    "Morigaon",
    "Nagaon",
    "Nalbari",
    "Sivasagar",
    "Sonitpur",
    "South Salmara-Mankachar",
    "Tinsukia",
    "Udalguri",
    "West Karbi Anglong",
  ],
  Bihar: [
    "Araria",
    "Arwal",
    "Aurangabad",
    "Banka",
    "Begusarai",
    "Bhagalpur",
    "Bhojpur",
    "Buxar",
    "Darbhanga",
    "East Champaran",
    "Gaya",
    "Gopalganj",
    "Jamui",
    "Jehanabad",
    "Kaimur",
    "Katihar",
    "Khagaria",
    "Kishanganj",
    "Lakhisarai",
    "Madhepura",
    "Madhubani",
    "Munger",
    "Muzaffarpur",
    "Nalanda",
    "Nawada",
    "Patna",
    "Purnia",
    "Rohtas",
    "Saharsa",
    "Samastipur",
    "Saran",
    "Sheikhpura",
    "Sheohar",
    "Sitamarhi",
    "Siwan",
    "Supaul",
    "Vaishali",
    "West Champaran",
  ],
  Chandigarh: ["Chandigarh"],
  Chhattisgarh: [
    "Balod",
    "Baloda Bazar",
    "Balrampur",
    "Bastar",
    "Bemetara",
    "Bijapur",
    "Bilaspur",
    "Dantewada",
    "Dhamtari",
    "Durg",
    "Gariaband",
    "Gaurela Pendra Marwahi",
    "Janjgir Champa",
    "Jashpur",
    "Kabirdham",
    "Kanker",
    "Kondagaon",
    "Korba",
    "Koriya",
    "Mahasamund",
    "Mungeli",
    "Narayanpur",
    "Raigarh",
    "Raipur",
    "Rajnandgaon",
    "Sukma",
    "Surajpur",
    "Surguja",
  ],
  "Daman Diu": ["Daman", "Diu"],
  "Dadra Nagar Haveli": ["Dadra Nagar Haveli"],
  Delhi: [
    "Central Delhi",
    "East Delhi",
    "New Delhi",
    "North Delhi",
    "North East Delhi",
    "North West Delhi",
    "Shahdara",
    "South Delhi",
    "South East Delhi",
    "South West Delhi",
    "West Delhi",
  ],
  Goa: ["North Goa", "South Goa"],
  Gujarat: [
    "Ahmedabad",
    "Amreli",
    "Anand",
    "Aravalli",
    "Banaskantha",
    "Bharuch",
    "Bhavnagar",
    "Botad",
    "Chhota Udaipur",
    "Dahod",
    "Dang",
    "Devbhoomi Dwarka",
    "Gandhinagar",
    "Gir Somnath",
    "Jamnagar",
    "Junagadh",
    "Kheda",
    "Kutch",
    "Mahisagar",
    "Mehsana",
    "Morbi",
    "Narmada",
    "Navsari",
    "Panchmahal",
    "Patan",
    "Porbandar",
    "Rajkot",
    "Sabarkantha",
    "Surat",
    "Surendranagar",
    "Tapi",
    "Vadodara",
    "Valsad",
  ],
  Haryana: [
    "Ambala",
    "Bhiwani",
    "Charkhi Dadri",
    "Faridabad",
    "Fatehabad",
    "Gurugram",
    "Hisar",
    "Jhajjar",
    "Jind",
    "Kaithal",
    "Karnal",
    "Kurukshetra",
    "Mahendragarh",
    "Mewat",
    "Palwal",
    "Panchkula",
    "Panipat",
    "Rewari",
    "Rohtak",
    "Sirsa",
    "Sonipat",
    "Yamunanagar",
  ],
  "Himachal Pradesh": [
    "Bilaspur",
    "Chamba",
    "Hamirpur",
    "Kangra",
    "Kinnaur",
    "Kullu",
    "Lahaul Spiti",
    "Mandi",
    "Shimla",
    "Sirmaur",
    "Solan",
    "Una",
  ],
  "Jammu Kashmir": [
    "Anantnag",
    "Bandipora",
    "Baramulla",
    "Budgam",
    "Doda",
    "Ganderbal",
    "Jammu",
    "Kathua",
    "Kishtwar",
    "Kulgam",
    "Kupwara",
    "Poonch",
    "Pulwama",
    "Rajouri",
    "Ramban",
    "Reasi",
    "Samba",
    "Shopian",
    "Srinagar",
    "Udhampur",
  ],
  Jharkhand: [
    "Bokaro",
    "Chatra",
    "Deoghar",
    "Dhanbad",
    "Dumka",
    "East Singhbhum",
    "Garhwa",
    "Giridih",
    "Godda",
    "Gumla",
    "Hazaribagh",
    "Jamtara",
    "Khunti",
    "Koderma",
    "Latehar",
    "Lohardaga",
    "Pakur",
    "Palamu",
    "Ramgarh",
    "Ranchi",
    "Sahebganj",
    "Seraikela Kharsawan",
    "Simdega",
    "West Singhbhum",
  ],
  Karnataka: [
    "Bagalkot",
    "Bangalore Rural",
    "Bangalore Urban",
    "Belgaum",
    "Bellary",
    "Bidar",
    "Chamarajanagar",
    "Chikkaballapur",
    "Chikkamagaluru",
    "Chitradurga",
    "Dakshina Kannada",
    "Davanagere",
    "Dharwad",
    "Gadag",
    "Gulbarga",
    "Hassan",
    "Haveri",
    "Kodagu",
    "Kolar",
    "Koppal",
    "Mandya",
    "Mysore",
    "Raichur",
    "Ramanagara",
    "Shimoga",
    "Tumkur",
    "Udupi",
    "Uttara Kannada",
    "Vijayapura",
    "Yadgir",
  ],
  Kerala: [
    "Alappuzha",
    "Ernakulam",
    "Idukki",
    "Kannur",
    "Kasaragod",
    "Kollam",
    "Kottayam",
    "Kozhikode",
    "Malappuram",
    "Palakkad",
    "Pathanamthitta",
    "Thiruvananthapuram",
    "Thrissur",
    "Wayanad",
  ],
  Ladakh: ["Kargil", "Leh"],
  Lakshadweep: ["Lakshadweep"],
  "Madhya Pradesh": [
    "Agar Malwa",
    "Alirajpur",
    "Anuppur",
    "Ashoknagar",
    "Balaghat",
    "Barwani",
    "Betul",
    "Bhind",
    "Bhopal",
    "Burhanpur",
    "Chachaura",
    "Chhatarpur",
    "Chhindwara",
    "Damoh",
    "Datia",
    "Dewas",
    "Dhar",
    "Dindori",
    "Guna",
    "Gwalior",
    "Harda",
    "Hoshangabad",
    "Indore",
    "Jabalpur",
    "Jhabua",
    "Katni",
    "Khandwa",
    "Khargone",
    "Maihar",
    "Mandla",
    "Mandsaur",
    "Morena",
    "Nagda",
    "Narsinghpur",
    "Neemuch",
    "Niwari",
    "Panna",
    "Raisen",
    "Rajgarh",
    "Ratlam",
    "Rewa",
    "Sagar",
    "Satna",
    "Sehore",
    "Seoni",
    "Shahdol",
    "Shajapur",
    "Sheopur",
    "Shivpuri",
    "Sidhi",
    "Singrauli",
    "Tikamgarh",
    "Ujjain",
    "Umaria",
    "Vidisha",
  ],
  Maharashtra: [
    "Ahmednagar",
    "Akola",
    "Amravati",
    "Aurangabad",
    "Beed",
    "Bhandara",
    "Buldhana",
    "Chandrapur",
    "Dhule",
    "Gadchiroli",
    "Gondia",
    "Hingoli",
    "Jalgaon",
    "Jalna",
    "Kolhapur",
    "Latur",
    "Mumbai City",
    "Mumbai Suburban",
    "Nagpur",
    "Nanded",
    "Nandurbar",
    "Nashik",
    "Osmanabad",
    "Palghar",
    "Parbhani",
    "Pune",
    "Raigad",
    "Ratnagiri",
    "Sangli",
    "Satara",
    "Sindhudurg",
    "Solapur",
    "Thane",
    "Wardha",
    "Washim",
    "Yavatmal",
  ],
  Manipur: [
    "Bishnupur",
    "Chandel",
    "Churachandpur",
    "Imphal East",
    "Imphal West",
    "Jiribam",
    "Kakching",
    "Kamjong",
    "Kangpokpi",
    "Noney",
    "Pherzawl",
    "Senapati",
    "Tamenglong",
    "Tengnoupal",
    "Thoubal",
    "Ukhrul",
  ],
  Meghalaya: [
    "East Garo Hills",
    "East Jaintia Hills",
    "East Khasi Hills",
    "North Garo Hills",
    "Ri Bhoi",
    "South Garo Hills",
    "South West Garo Hills",
    "South West Khasi Hills",
    "West Garo Hills",
    "West Jaintia Hills",
    "West Khasi Hills",
  ],
  Mizoram: [
    "Aizawl",
    "Champhai",
    "Kolasib",
    "Lawngtlai",
    "Lunglei",
    "Mamit",
    "Saiha",
    "Serchhip",
  ],
  Nagaland: [
    "Dimapur",
    "Kiphire",
    "Kohima",
    "Longleng",
    "Mokokchung",
    "Mon",
    "Noklak",
    "Peren",
    "Phek",
    "Tuensang",
    "Wokha",
    "Zunheboto",
  ],
  Odisha: [
    "Angul",
    "Balangir",
    "Balasore",
    "Bargarh",
    "Bhadrak",
    "Boudh",
    "Cuttack",
    "Debagarh",
    "Dhenkanal",
    "Gajapati",
    "Ganjam",
    "Jagatsinghpur",
    "Jajpur",
    "Jharsuguda",
    "Kalahandi",
    "Kandhamal",
    "Kendrapara",
    "Kendujhar",
    "Khordha",
    "Koraput",
    "Malkangiri",
    "Mayurbhanj",
    "Nabarangpur",
    "Nayagarh",
    "Nuapada",
    "Puri",
    "Rayagada",
    "Sambalpur",
    "Subarnapur",
    "Sundergarh",
  ],
  Puducherry: ["Karaikal", "Mahe", "Puducherry", "Yanam"],
  Punjab: [
    "Amritsar",
    "Barnala",
    "Bathinda",
    "Faridkot",
    "Fatehgarh Sahib",
    "Fazilka",
    "Firozpur",
    "Gurdaspur",
    "Hoshiarpur",
    "Jalandhar",
    "Kapurthala",
    "Ludhiana",
    "Mansa",
    "Moga",
    "Mohali",
    "Muktsar",
    "Pathankot",
    "Patiala",
    "Rupnagar",
    "Sangrur",
    "Shaheed Bhagat Singh Nagar",
    "Tarn Taran",
  ],
  Rajasthan: [
    "Ajmer",
    "Alwar",
    "Banswara",
    "Baran",
    "Barmer",
    "Bharatpur",
    "Bhilwara",
    "Bikaner",
    "Bundi",
    "Chittorgarh",
    "Churu",
    "Dausa",
    "Dholpur",
    "Dungarpur",
    "Hanumangarh",
    "Jaipur",
    "Jaisalmer",
    "Jalore",
    "Jhalawar",
    "Jhunjhunu",
    "Jodhpur",
    "Karauli",
    "Kota",
    "Nagaur",
    "Pali",
    "Pratapgarh",
    "Rajsamand",
    "Sawai Madhopur",
    "Sikar",
    "Sirohi",
    "Sri Ganganagar",
    "Tonk",
    "Udaipur",
  ],
  Sikkim: ["East Sikkim", "North Sikkim", "South Sikkim", "West Sikkim"],
  "Tamil Nadu": [
    "Ariyalur",
    "Chengalpattu",
    "Chennai",
    "Coimbatore",
    "Cuddalore",
    "Dharmapuri",
    "Dindigul",
    "Erode",
    "Kallakurichi",
    "Kanchipuram",
    "Kanyakumari",
    "Karur",
    "Krishnagiri",
    "Madurai",
    "Mayiladuthurai",
    "Nagapattinam",
    "Namakkal",
    "Nilgiris",
    "Perambalur",
    "Pudukkottai",
    "Ramanathapuram",
    "Ranipet",
    "Salem",
    "Sivaganga",
    "Tenkasi",
    "Thanjavur",
    "Theni",
    "Thoothukudi",
    "Tiruchirappalli",
    "Tirunelveli",
    "Tirupathur",
    "Tiruppur",
    "Tiruvallur",
    "Tiruvannamalai",
    "Tiruvarur",
    "Vellore",
    "Viluppuram",
    "Virudhunagar",
  ],
  Telangana: [
    "Adilabad",
    "Bhadradri Kothagudem",
    "Hyderabad",
    "Jagtial",
    "Jangaon",
    "Jayashankar Bhupalpally",
    "Jogulamba Gadwal",
    "Kamareddy",
    "Karimnagar",
    "Khammam",
    "Komaram Bheem",
    "Mahabubabad",
    "Mahbubnagar",
    "Mancherial",
    "Medak",
    "Medchal-Malkajgiri",
    "Mulugu",
    "Nagarkurnool",
    "Nalgonda",
    "Nirmal",
    "Nizamabad",
    "Peddapalli",
    "Rajanna Sircilla",
    "Ranga Reddy",
    "Sangareddy",
    "Siddipet",
    "Suryapet",
    "Vikarabad",
    "Wanaparthy",
    "Warangal Rural",
    "Warangal Urban",
    "Yadadri Bhuvanagiri",
  ],
  Tripura: [
    "Dhalai",
    "Gomati",
    "Khowai",
    "North Tripura",
    "Sepahijala",
    "South Tripura",
    "Unakoti",
    "West Tripura",
  ],
  "Uttar Pradesh": [
    "Agra",
    "Aligarh",
    "Ambedkar Nagar",
    "Amethi",
    "Amroha",
    "Auraiya",
    "Ayodhya",
    "Azamgarh",
    "Baghpat",
    "Bahraich",
    "Ballia",
    "Balrampur",
    "Banda",
    "Barabanki",
    "Bareilly",
    "Basti",
    "Bhadohi",
    "Bijnor",
    "Budaun",
    "Bulandshahr",
    "Chandauli",
    "Chitrakoot",
    "Deoria",
    "Etah",
    "Etawah",
    "Farrukhabad",
    "Fatehpur",
    "Firozabad",
    "Gautam Buddha Nagar",
    "Ghaziabad",
    "Ghazipur",
    "Gonda",
    "Gorakhpur",
    "Hamirpur",
    "Hapur",
    "Hardoi",
    "Hathras",
    "Jalaun",
    "Jaunpur",
    "Jhansi",
    "Kannauj",
    "Kanpur Dehat",
    "Kanpur Nagar",
    "Kasganj",
    "Kaushambi",
    "Kushinagar",
    "Lakhimpur Kheri",
    "Lalitpur",
    "Lucknow",
    "Maharajganj",
    "Mahoba",
    "Mainpuri",
    "Mathura",
    "Mau",
    "Meerut",
    "Mirzapur",
    "Moradabad",
    "Muzaffarnagar",
    "Pilibhit",
    "Pratapgarh",
    "Prayagraj",
    "Raebareli",
    "Rampur",
    "Saharanpur",
    "Sambhal",
    "Sant Kabir Nagar",
    "Shahjahanpur",
    "Shamli",
    "Shrawasti",
    "Siddharthnagar",
    "Sitapur",
    "Sonbhadra",
    "Sultanpur",
    "Unnao",
    "Varanasi",
  ],
  Uttarakhand: [
    "Almora",
    "Bageshwar",
    "Chamoli",
    "Champawat",
    "Dehradun",
    "Haridwar",
    "Nainital",
    "Pauri Garhwal",
    "Pithoragarh",
    "Rudraprayag",
    "Tehri Garhwal",
    "Udham Singh Nagar",
    "Uttarkashi",
  ],
  "West Bengal": [
    "Alipurduar",
    "Bankura",
    "Birbhum",
    "Cooch Behar",
    "Dakshin Dinajpur",
    "Darjeeling",
    "Hooghly",
    "Howrah",
    "Jalpaiguri",
    "Jhargram",
    "Kalimpong",
    "Kolkata",
    "Malda",
    "Murshidabad",
    "Nadia",
    "North 24 Parganas",
    "Paschim Bardhaman",
    "Paschim Medinipur",
    "Purba Bardhaman",
    "Purba Medinipur",
    "Purulia",
    "South 24 Parganas",
    "Uttar Dinajpur",
  ],
};
